### ISSUE TITLE
Revisit public/private methods

### ISSUE THREAD

**Issue by ecsalomon** [dssg/timechop#12]
Speedy development got a bit sloppy. Good idea to revisit what should be public/private methods and make sure there are tests for the public ones.

**Comment by thcrock** [comment]
Test coverage post-https://github.com/dssg/timechop/pull/72 will be 100%, but a point here still stands about public vs private methods. It's unclear whether the non-chop_time methods are part of the interface or just internal. I'll change the name of the issue.

As far as the parts of the codebase that have been moved to the Architect repo since this issue was created, test coverage and public/private demarcation looks like it's been addressed over time, so I won't recreate a version of this there.

**Comment by jesteria** [comment]
This issue was moved to dssg/triage#315
