### ISSUE TITLE
Allow passing a list of feature tables to use

### ISSUE THREAD

**Issue by ecsalomon** [dssg/timechop#13]
Right now, the architect uses all tables in the feature schema except for a short blacklist, but this is somewhat dangerous. Better to have the user (or pipeline) generate a white list of tables to use and pass that. If None is passed, it can default to current behavior and warn.

**Comment by thcrock** [comment]
I think this is a bit more important now. The blacklist is currently sent in the constructor, which creates a data dependency in the constructor (we'd rather instantiate the architect before we start running queries). We could sidestep this by passing a list of feature table exclusions to chop_data, but then we would have to pass it down a few levels to get to where it needs to be. It would probably be easier to tackle the whitelist task instead.

This got me thinking: should the entire feature dictionary be input, instead of just the list of the feature tables? The feature dictionary seems more naturally computed elsewhere, closer to where features are generated. We could move this code elsewhere (maybe triage.FeatureGenerator for now), and allow the final feature dictionary to be passed as input to chop_data.

**Comment by ecsalomon** [comment]
Yeah, I think I agree with this.
